// packages/angular/src/skeleton/skeleton.component.ts
import {
  Component,
  Input,
  OnChanges,
  ChangeDetectionStrategy,
  signal,
  computed,
} from '@angular/core';

@Component({
  selector: 'mv-skeleton',
  standalone: true,
  template: `
    <div
      [class]="hostClass()"
      [style.width]="hostWidth()"
      [style.height]="hostHeight()"
      aria-busy="true"
    ></div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SkeletonComponent implements OnChanges {
  @Input() variant: 'text' | 'circle' | 'rect' = 'text';
  @Input() animation: 'shimmer' | 'pulse' | 'wave' | 'none' = 'shimmer';
  @Input() width?: string | number;
  @Input() height?: string | number;

  readonly _variant = signal<'text' | 'circle' | 'rect'>('text');
  readonly _animation = signal<'shimmer' | 'pulse' | 'wave' | 'none'>('shimmer');
  readonly _width = signal<string | number | undefined>(undefined);
  readonly _height = signal<string | number | undefined>(undefined);

  ngOnChanges(): void {
    this._variant.set(this.variant);
    this._animation.set(this.animation);
    this._width.set(this.width);
    this._height.set(this.height);
  }

  readonly hostClass = computed(() => {
    const classes = ['mv-skeleton', `mv-skeleton--${this._variant()}`];
    if (this._animation() !== 'none') {
      classes.push(`mv-skeleton--${this._animation()}`);
    }
    return classes.join(' ');
  });

  private formatSize(val?: string | number): string {
    if (val === undefined || val === null) return '';
    if (typeof val === 'number') return `${val}px`;
    return val;
  }

  readonly hostWidth = computed(() => this.formatSize(this._width()));
  readonly hostHeight = computed(() => this.formatSize(this._height()));
}

// packages/react/src/Skeleton/Skeleton.tsx
import React from 'react';
import { SkeletonProps } from './Skeleton.types.js';

export function Skeleton({
  variant = 'text',
  animation = 'shimmer',
  width,
  height,
  className = '',
  style,
  ...props
}: SkeletonProps) {
  const classes = [
    'mv-skeleton',
    `mv-skeleton--${variant}`,
    animation !== 'none' ? `mv-skeleton--${animation}` : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const formatSize = (val?: string | number) => {
    if (typeof val === 'number') return `${val}px`;
    return val;
  };

  const inlineStyles: React.CSSProperties = {
    ...style,
    width: formatSize(width),
    height: formatSize(height),
  };

  return <div className={classes} style={inlineStyles} aria-busy="true" {...props} />;
}
