// packages/react/src/KpiCard.tsx
// @ts-nocheck
import React, { useEffect, useRef } from "react";
import { initKpiCards } from "mayvio-ui/scripts/components/kpi-card.js";

/**
 * KpiCard
 * React wrapper for Mayvio UI KPI Card with viewport-triggered animated counter.
 *
 * Props:
 * - title: string, title of the card
 * - value: number, target value for counter animation
 * - icon: ReactNode, optional icon
 * - trend: string, trend percentage (e.g. '12%')
 * - trendDirection: 'up' | 'down', colors and styles the trend indicator
 * - footer: string, footer description
 * - duration: animation duration in milliseconds
 * - decimals: number of decimal places
 * - prefix: string prefix (e.g. '$')
 * - suffix: string suffix (e.g. '%')
 * - className: custom class names
 */
export function KpiCard({
  title,
  value,
  icon,
  trend,
  trendDirection,
  footer,
  duration = 1500,
  decimals = 0,
  prefix = "",
  suffix = "",
  className = ""
}) {
  const valueRef = useRef(null);

  useEffect(() => {
    if (valueRef.current) {
      // Re-trigger viewport animation on value update
      initKpiCards(valueRef.current);
    }
  }, [value]);

  return (
    <div className={`kpi-card ${className}`}>
      <div className="kpi-card-header">
        <span className="kpi-card-title">{title}</span>
        {icon && <span className="kpi-card-icon">{icon}</span>}
      </div>
      <div className="kpi-card-body">
        <span
          ref={valueRef}
          className="kpi-card-value"
          data-value={value}
          data-duration={duration}
          data-decimals={decimals}
          data-prefix={prefix}
          data-suffix={suffix}
        >
          {prefix}0{suffix}
        </span>
        {trend && (
          <span className={`kpi-card-trend ${trendDirection}`}>
            {trendDirection === "up" ? "↑" : "↓"} {trend}
          </span>
        )}
      </div>
      {footer && <div className="kpi-card-footer">{footer}</div>}
    </div>
  );
}

// packages/angular/src/kpi-card.component.ts
// @ts-nocheck
import { Component, Input, OnInit, ElementRef } from "@angular/core";
import { initKpiCards } from "mayvio-ui/scripts/components/kpi-card.js";

/**
 * KpiCardComponent
 * Angular wrapper component representing the Mayvio UI KPI Card.
 */
@Component({
  selector: "mayvio-kpi-card",
  template: `
    <div class="kpi-card {{ className }}">
      <div class="kpi-card-header">
        <span class="kpi-card-title">{{ title }}</span>
        <span *ngIf="icon" class="kpi-card-icon">{{ icon }}</span>
      </div>
      <div class="kpi-card-body">
        <span
          class="kpi-card-value"
          [attr.data-value]="value"
          [attr.data-duration]="duration"
          [attr.data-decimals]="decimals"
          [attr.data-prefix]="prefix"
          [attr.data-suffix]="suffix"
        >
          {{ prefix }}0{{ suffix }}
        </span>
        <span *ngIf="trend" class="kpi-card-trend {{ trendDirection }}">
          {{ trendDirection === "up" ? "↑" : "↓" }} {{ trend }}
        </span>
      </div>
      <div *ngIf="footer" class="kpi-card-footer">{{ footer }}</div>
    </div>
  `
})
export class KpiCardComponent implements OnInit {
  @Input() title = "";
  @Input() value = 0;
  @Input() icon = "";
  @Input() trend = "";
  @Input() trendDirection: "up" | "down" = "up";
  @Input() footer = "";
  @Input() duration = 1500;
  @Input() decimals = 0;
  @Input() prefix = "";
  @Input() suffix = "";
  @Input() className = "";

  constructor(private el: ElementRef) {}

  ngOnInit() {
    const valNode = this.el.nativeElement.querySelector(".kpi-card-value");
    if (valNode) {
      initKpiCards(valNode);
    }
  }
}
