// packages/angular/src/chart.component.ts
// @ts-nocheck
import { Component, Input, OnInit, ElementRef, OnChanges, SimpleChanges } from "@angular/core";
import { MayvioChart } from "mayvio-ui/scripts/components/chart.js";

/**
 * ChartComponent
 * Angular wrapper component representing the SVG-based charts.
 */
@Component({
  selector: "mayvio-chart",
  template: `
    <div class="chart-container {{ className }}">
      <div *ngIf="title" class="chart-header">
        <div class="chart-title">{{ title }}</div>
      </div>
      <div class="canvas-holder"></div>
    </div>
  `
})
export class ChartComponent implements OnInit, OnChanges {
  @Input() type = "line";
  @Input() data: any = { labels: [], datasets: [] };
  @Input() options: any = {};
  @Input() title = "";
  @Input() className = "";

  constructor(private el: ElementRef) {}

  ngOnInit() {
    this.createChart();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (
      (changes["type"] || changes["data"] || changes["options"]) &&
      !changes["data"]?.isFirstChange()
    ) {
      this.createChart();
    }
  }

  private createChart() {
    const holder = this.el.nativeElement.querySelector(".canvas-holder");
    if (holder) {
      new MayvioChart(holder, {
        type: this.type,
        data: this.data,
        options: this.options
      });
    }
  }
}

// packages/react/src/Chart.tsx
// @ts-nocheck
import React, { useEffect, useRef } from "react";
import { MayvioChart } from "mayvio-ui/scripts/components/chart.js";

/**
 * Chart
 * React wrapper for Mayvio UI SVG-based Line, Bar, and Donut charts.
 *
 * Props:
 * - type: 'line' | 'bar' | 'donut'
 * - data: { labels: string[], datasets: Dataset[] }
 * - options: ChartConfigOptions
 * - title: string header title
 * - className: custom class names
 */
export function Chart({ type = "line", data, options = {}, title, className = "" }) {
  const canvasRef = useRef(null);

  useEffect(() => {
    if (canvasRef.current) {
      new MayvioChart(canvasRef.current, {
        type,
        data,
        options
      });
    }
  }, [type, data, options]);

  return (
    <div className={`chart-container ${className}`}>
      {title && (
        <div className="chart-header">
          <div className="chart-title">{title}</div>
        </div>
      )}
      <div ref={canvasRef} />
    </div>
  );
}
