// packages/react/src/Checkbox/Checkbox.tsx
import { forwardRef, useEffect, useRef } from 'react';
import { CheckboxProps } from './Checkbox.types.js';
import 'mayvio-ui/checkbox/css';

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  ({ className = '', label, error = false, disabled = false, indeterminate = false, checked, onChange, ...props }, ref) => {
    const internalRef = useRef<HTMLInputElement | null>(null);

    const setRefs = (node: HTMLInputElement | null) => {
      internalRef.current = node;
      if (typeof ref === 'function') {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    };

    useEffect(() => {
      if (internalRef.current) {
        internalRef.current.indeterminate = indeterminate;
      }
    }, [indeterminate]);

    return (
      <label className={`mv-checkbox-wrapper ${disabled ? 'mv-checkbox-wrapper--disabled' : ''} ${error ? 'mv-checkbox-wrapper--error' : ''} ${className}`}>
        <input
          ref={setRefs}
          type="checkbox"
          className="mv-checkbox-input"
          disabled={disabled}
          checked={checked}
          onChange={onChange}
          {...props}
        />
        <div className="mv-checkbox-control" aria-hidden="true">
          <svg className="mv-checkbox-icon" viewBox="0 0 15 15">
            {indeterminate ? (
              <path d="M4 7.5H11" strokeWidth="2" />
            ) : (
              <path d="M3.5 7.5L6 10L11.5 4" strokeWidth="2" />
            )}
          </svg>
        </div>
        {label && <span className="mv-checkbox-label">{label}</span>}
      </label>
    );
  }
);

Checkbox.displayName = 'Checkbox';

// packages/angular/src/checkbox/checkbox.component.ts
import { Component, ChangeDetectionStrategy, Input, forwardRef, ViewEncapsulation, ViewChild, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';
import { CheckboxConfig } from 'mayvio-ui/checkbox';
import 'mayvio-ui/checkbox/css';

@Component({
  selector: 'mv-checkbox',
  standalone: true,
  imports: [CommonModule],
  template: `
    <label [class]="'mv-checkbox-wrapper' + (disabled ? ' mv-checkbox-wrapper--disabled' : '') + (error ? ' mv-checkbox-wrapper--error' : '') + (className ? ' ' + className : '')">
      <input
        #inputRef
        type="checkbox"
        class="mv-checkbox-input"
        [disabled]="disabled"
        [checked]="checked"
        (change)="onChangeEvent($event)"
        (blur)="onTouched()"
      />
      <div class="mv-checkbox-control" aria-hidden="true">
        <svg class="mv-checkbox-icon" viewBox="0 0 15 15">
          <ng-container *ngIf="indeterminate; else checkIcon">
            <path d="M4 7.5H11" stroke-width="2" />
          </ng-container>
          <ng-template #checkIcon>
            <path d="M3.5 7.5L6 10L11.5 4" stroke-width="2" />
          </ng-template>
        </svg>
      </div>
      <span *ngIf="label" class="mv-checkbox-label">{{ label }}</span>
    </label>
  `,
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi: true,
    },
  ],
})
export class CheckboxComponent implements ControlValueAccessor, CheckboxConfig, OnChanges {
  @Input() label?: string;
  @Input() error = false;
  @Input() disabled = false;
  @Input() indeterminate = false;
  @Input() checked = false;
  @Input() className = '';

  @ViewChild('inputRef') inputRef!: ElementRef<HTMLInputElement>;

  onChange = (val: boolean) => {};
  onTouched = () => {};

  ngOnChanges(changes: SimpleChanges) {
    if (changes['indeterminate'] && this.inputRef) {
      this.inputRef.nativeElement.indeterminate = this.indeterminate;
    }
  }

  onChangeEvent(event: Event) {
    const val = (event.target as HTMLInputElement).checked;
    this.checked = val;
    this.onChange(val);
  }

  writeValue(value: boolean): void {
    this.checked = !!value;
  }
  registerOnChange(fn: any): void {
    this.onChange = fn;
  }
  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }
  setDisabledState?(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}
