// packages/react/src/Avatar/Avatar.tsx
import React from 'react';
import { AvatarProps, AvatarGroupProps } from './Avatar.types.js';

export function Avatar({
  src,
  alt = '',
  initials,
  size = 'md',
  shape = 'circle',
  status,
  className = '',
  ...props
}: AvatarProps) {
  const classes = [
    'mv-avatar',
    `mv-avatar--${size}`,
    shape === 'square' ? 'mv-avatar--square' : '',
    status ? `mv-avatar--${status}` : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <span className={classes} {...props}>
      {src ? (
        <img className="mv-avatar__image" src={src} alt={alt} />
      ) : initials ? (
        <span className="mv-avatar__initials" aria-hidden="true">
          {initials}
        </span>
      ) : null}
    </span>
  );
}

export function AvatarGroup({
  size = 'md',
  limit,
  children,
  className = '',
  ...props
}: AvatarGroupProps) {
  const childArray = React.Children.toArray(children);
  const visible = limit != null ? childArray.slice(0, limit) : childArray;
  const overflow = limit != null && childArray.length > limit ? childArray.length - limit : 0;

  const classes = ['mv-avatar-group', `mv-avatar-group--${size}`, className]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} {...props}>
      {visible}
      {overflow > 0 && (
        <span className="mv-avatar-group__overflow" aria-label={`${overflow} more`}>
          +{overflow}
        </span>
      )}
    </div>
  );
}

// packages/angular/src/avatar/avatar.component.ts
import {
  Component,
  Input,
  OnChanges,
  ChangeDetectionStrategy,
  signal,
  computed,
} from '@angular/core';
import { NgIf } from '@angular/common';

@Component({
  selector: 'mv-avatar',
  standalone: true,
  imports: [NgIf],
  template: `
    <span [class]="hostClass()">
      <img *ngIf="_src()" class="mv-avatar__image" [src]="_src()" [attr.alt]="_alt()" />
      <span *ngIf="!_src() && _initials()" class="mv-avatar__initials" aria-hidden="true">{{
        _initials()
      }}</span>
    </span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarComponent implements OnChanges {
  @Input() src = '';
  @Input() alt = '';
  @Input() initials = '';
  @Input() size: 'sm' | 'md' | 'lg' | 'xl' = 'md';
  @Input() shape: 'circle' | 'square' = 'circle';
  @Input() status: 'online' | 'offline' | 'busy' | '' = '';

  readonly _src = signal('');
  readonly _alt = signal('');
  readonly _initials = signal('');
  readonly _size = signal<'sm' | 'md' | 'lg' | 'xl'>('md');
  readonly _shape = signal<'circle' | 'square'>('circle');
  readonly _status = signal<'online' | 'offline' | 'busy' | ''>('');

  ngOnChanges(): void {
    this._src.set(this.src);
    this._alt.set(this.alt);
    this._initials.set(this.initials);
    this._size.set(this.size);
    this._shape.set(this.shape);
    this._status.set(this.status);
  }

  readonly hostClass = computed(() => {
    const classes = ['mv-avatar', `mv-avatar--${this._size()}`];
    if (this._shape() === 'square') classes.push('mv-avatar--square');
    if (this._status()) classes.push(`mv-avatar--${this._status()}`);
    return classes.join(' ');
  });
}

@Component({
  selector: 'mv-avatar-group',
  standalone: true,
  template: `
    <div [class]="hostClass()">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarGroupComponent {
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() limit?: number;

  readonly hostClass = computed(() =>
    ['mv-avatar-group', `mv-avatar-group--${this.size}`].join(' ')
  );
}
